- group_project_v2/group_activity.py
- group_project_v2/res/default.xml
- tests/unit/test_xml_parsing.py
- tests/xml/test.xml
> Submissions in stages

- group_project_v2/components/activity.py
- group_project_v2/components/stage.py
- group_project_v2/group_project.py
- group_project_v2/utils.py
> Validations

- group_project_v2/group_project.py
- group_project_v2/project_api.py
Forward-porting https://github.com/edx-solutions/xblock-group-project/pull/49 - see there for description and testing instructions
> (MCKIN-3164) Fixed issue in groupwork grading

- group_project_v2/group_project.py
- group_project_v2/mixins.py
- group_project_v2/project_navigator.py
- group_project_v2/stage.py
- group_project_v2/stage_components.py
- group_project_v2/utils.py
- setup.py
* Tweaking default stage - should show first open and incomplete
* Streamlined rendering studio add buttons, fixed a couple of issues with that.
> Final improvements for real children conversion

- group_project_v2/stage.py
* Individual `display_name` fields for all stages - need to provide unique default names
* Fixed incorrect studio label for "Text" stage
> Studio fixes

- group_project_v2/public/css/project_navigator/project_navigator.css
Missing styling fix - PN moved to far to right
> Styling pass 1.5

- group_project_v2/project_navigator.py
- group_project_v2/public/css/project_navigator/submissions_view.css
- group_project_v2/templates/html/components/submission_navigator_view.html
- group_project_v2/templates/html/project_navigator/ask_ta_view.html
- group_project_v2/templates/html/project_navigator/resources_view.html
- group_project_v2/templates/html/project_navigator/submissions_view.html
* More PN view title updates
* Wider PN (35% width)
* Submissions view styling: borders around input controls, updated placeholder text
> More fixes from QA

- group_project_v2/public/css/project_navigator/resources_view.css
- group_project_v2/stage_components.py
* "Review Question ..." review questions title prefix  in stuido
* Resources should have bullets in PN Resources view
> A couple of styling issues found in QA

- group_project_v2/project_api.py
- tests/unit/test_group_project.py
- tests/unit/test_mixins.py
- tests/unit/test_project_api.py
- tests/unit/test_stage_components.py
Addressed notes and improved test coverage for project_api
> Unit testing - part 2

- group_project_v2/mixins.py
- group_project_v2/stage.py
- tests/integration/page_elements.py
- tests/integration/test_stages.py
- tests/unit/test_mixins.py
Port of https://github.com/edx-solutions/xblock-group-project/pull/50 to GP v2
> [MCKIN-3050] Enabling TA view even when a TA is a group member

- group_project_v2/group_project.py
- group_project_v2/mixins.py
- group_project_v2/project_navigator.py
- group_project_v2/stage.py
- group_project_v2/stage_components.py
- group_project_v2/utils.py
- tests/unit/test_group_project.py
- tests/unit/test_mixins.py
- tests/unit/test_stage_components.py
- tests/unit/test_utils.py
- tests/utils.py
- tests/xml/example_1.xml
Filters questions according to types in feedback display components and displays selector as dropdown (used to be simple text field)
Depends on #51
> Question selector dropdown

- group_project_v2/public/css/components/project_team.css
- group_project_v2/public/css/group_project.css
- group_project_v2/stage_components.py
- requirements.txt
- tests/unit/test_stage_components.py
Fixes the following bugs:
* https://edx-wiki.atlassian.net/browse/MCKIN-3499
* https://edx-wiki.atlassian.net/browse/MCKIN-3485
* https://edx-wiki.atlassian.net/browse/MCKIN-3500
> Bugfixes part 4

- group_project_v2/project_api.py
- group_project_v2/public/js/components/submission.js
- group_project_v2/public/js/stages/review_stage.js
- group_project_v2/stage.py
- group_project_v2/stage_components.py
- group_project_v2/templates/html/components/review_assessment.html
- group_project_v2/templates/html/components/submission_navigator_view.html
- group_project_v2/templates/html/stages/grade_display.html
- test-requirements.txt
- tests/integration/test_project_navigator.py
- tests/integration/test_stages.py
- tests/unit/test_stage_components.py
- tests/utils.py
> Address several fixes from QA

- group_project_v2/mixins.py
- group_project_v2/project_navigator.py
- group_project_v2/public/css/components/project_team.css
- group_project_v2/public/css/components/review_subject_selector.css
- group_project_v2/stage_components.py
- group_project_v2/templates/html/components/group_selector.html
- tests/integration/base_test.py
- tests/integration/test_project_navigator.py
**What's in here:**
* https://edx-wiki.atlassian.net/browse/MCKIN-3473 UI - Change order of buttons on Project Navigator
* https://edx-wiki.atlassian.net/browse/MCKIN-3474 UI - Changes to text in confirmation popup for upload
* https://edx-wiki.atlassian.net/browse/MCKIN-3479 UI - change font size/style for evaluating label
* https://edx-wiki.atlassian.net/browse/MCKIN-3480 UI - margin and punctuation changes in peer grading stage in gwv2
* https://edx-wiki.atlassian.net/browse/MCKIN-3450 UI - Double line between TEAM and COMPLETION
> Another batch of presentation fixes

- group_project_v2/group_project.py
- group_project_v2/messages.py
- group_project_v2/mixins.py
- group_project_v2/project_api/dtos.py
- group_project_v2/project_navigator.py
- group_project_v2/public/css/group_project_common.css
- group_project_v2/public/css/group_project_dashboard.css
- group_project_v2/public/js/components/project_team.js
- group_project_v2/public/js/components/submission.js
- group_project_v2/public/js/group_project_dashboard_detail.js
- group_project_v2/public/js/project_navigator/ask_ta_view.js
- group_project_v2/public/js/project_navigator/submissions_view.js
- group_project_v2/public/js/stages/completion.js
- group_project_v2/public/js/stages/review_stage.js
- group_project_v2/stage/base.py
- group_project_v2/stage/basic.py
- group_project_v2/stage/feedback_review.py
- group_project_v2/stage/review.py
- group_project_v2/stage/utils.py
- group_project_v2/stage_components.py
- group_project_v2/templates/html/activity/dashboard_detail_view.html
- group_project_v2/templates/html/project/dashboard_detail_view.html
- group_project_v2/templates/html/stages/dashboard_detail_view.html
- group_project_v2/templates/html/stages/dashboard_view.html
- group_project_v2/utils.py
- tests/unit/test_group_project.py
- tests/unit/test_stage_components.py
- tests/unit/test_stages.py
**Configuration**
Add the following XBlock settings to lms.env.json
```
"XBLOCK_SETTINGS": {
"group_project_v2": {
"dashboard_details_url": "/admin/workgroup/dashboard/programs/{program_id}/courses/{course_id}/projects/{project_id}/details?activate_block_id={activity_id}",
"ta_review_url": "/courses/{course_id}/group_work/{group_id}?activate_block_id={activate_block_id}"
}
},
```
1. Configure GP so that at least one group have more than one participant
2. Complete non-TA graded Peer Grading stages by *some* users
3. Log in as McKA TA (username mcka_ta_user) or internal/company/McKA admin
4. Go to Admin dashboard -> Group Work -> Access V2 Dashboard
5. Choose program, course and project
6. Click on blue > in any stage that has it in bottom-right corner
7. You …
> Dashboard details view

- group_project_v2/public/css/group_project_dashboard.css
In this episode:
* [MCKIN-3669](https://edx-wiki.atlassian.net/browse/MCKIN-3669) - stages are not aligned (when some stage have long name)
* [MCKIN-3670](https://edx-wiki.atlassian.net/browse/MCKIN-3670) - stage height is not the same across all stages (when some stage have long name again)
* [MCKIN-3671](https://edx-wiki.atlassian.net/browse/MCKIN-3671) - activity titles are not vertically centered.
> UI, copy and styling fixes - part 4

- group_project_v2/group_project.py
- group_project_v2/public/js/components/project_team.js
- group_project_v2/public/js/components/review_subject_selector.js
- group_project_v2/public/js/components/submission.js
- group_project_v2/public/js/group_project.js
- group_project_v2/public/js/group_project_common.js
- group_project_v2/public/js/project_navigator/ask_ta_view.js
- group_project_v2/public/js/project_navigator/navigation_view.js
- group_project_v2/public/js/project_navigator/private_discussion_view.js
- group_project_v2/public/js/project_navigator/project_navigator.js
- group_project_v2/public/js/project_navigator/resources_view.js
- group_project_v2/public/js/project_navigator/submissions_view.js
- group_project_v2/public/js/stages/completion.js
- group_project_v2/public/js/stages/review_stage.js
- tests/js/test_review_subject_selector.js
- tests/js/test_suite_self_test.js
**Description:** This PR collects some "shared" js strings and methods to a single location.
**Testing instructions:** Run test suite + smoke test everything.
> Extracted common JS constants/methods to dedicated place

- group_project_v2/group_project.py
- group_project_v2/mixins.py
- group_project_v2/project_api/api_implementation.py
- group_project_v2/stage/base.py
- group_project_v2/utils.py
- tests/unit/test_mixins.py
- tests/unit/test_stages/test_base_stage.py
- tests/utils.py
**Descriptinon:** Adds support for filtering by company to main dashboard view
**Dependencies:** Builds on #85 
**Testing instructions:** See instructions on https://github.com/mckinseyacademy/mcka_apros/pull/1315
> Filter by company in main dashboard view

- .coveragerc
- .gitignore
- .travis.yml
- Makefile
- tests/js/karma.conf.js
Coverage improvements
* JS coverage to coverage/js
* python coverage to coverage/py
* branch coverage
> Coverage improvements

- README.md
When implementing OC-1463 I forgot to update docs.
> Added new key to configuration

- group_project_v2/templates/html/project_navigator/project_navigator.html
Group Work v2: Remove project navigator icon from Group Work v2
> MCKIN-4174

- group_project_v2/group_project.py
- setup.py
- tests/unit/test_group_project.py
Proficiency was not upgrading when grade value becomes 0. Fixed condition to accept 0 as new grade value.
> Fixed proficiency upgrade issue when grade is zero

- requirements/base.txt
- setup.py
Version bump PR for changes made [here](https://github.com/mckinseyacademy/django-upload-validator/pull/10).
> YONK-1306: Upload validator version bump

- group_project_v2/stage_components.py
- group_project_v2/upload_file.py
- group_project_v2/utils.py
- requirements/base.txt
- setup.py
- tests/unit/test_stage_components.py
Right now Group Work uploaded file are publicly accessible. 
Therefore making those URLs pre-signed so that it can be only accessed for a limited time period(30 Min for now).
> MCKIN-11136-make-s3-links-presigned

- Makefile
- group_project_v2/group_project.py
- group_project_v2/messages.py
- group_project_v2/mixins.py
- group_project_v2/project_navigator.py
- group_project_v2/public/js/group_project_common.js
- group_project_v2/stage/base.py
- group_project_v2/stage/basic.py
- group_project_v2/stage/feedback_review.py
- group_project_v2/stage/review.py
- group_project_v2/stage_components.py
- group_project_v2/templates/html/components/group_selector.html
- group_project_v2/templates/html/components/submission_navigator_view.html
- group_project_v2/templates/html/project_navigator/ask_ta_view.html
- group_project_v2/templates/html/project_navigator/resources_view.html
- group_project_v2/templates/html/project_navigator/submissions_view.html
- group_project_v2/templates/html/stages/navigation_view.html
- group_project_v2/templates/html/stages/peer_review.html
- group_project_v2/templates/html/stages/stage_wrapper.html
- group_project_v2/templates/html/stages/team_evaluation.html
- group_project_v2/utils.py
- pylintrc
- requirements/base.txt
- setup.py
- tests/unit/test_mixins.py
- tests/unit/test_stage_components.py
- tests/unit/test_stages/base.py
- tests/unit/test_stages/test_feedback_display.py
In order to make a Group project v2  translatable, I have integrated translation and added a minimal number of hooks to Python code and templates. By this PR, the text should be translated into the end user’s language.
Testing instructions:
-  checkout to this branch
- and to verify the strings are now getting translated for all languages.
> MCKIN-24383 xblock internationalization

- group_project_v2/public/js/group_project_common.js
- setup.py
Details are here: https://github.com/open-craft/xblock-group-project-v2/pull/158
> MCKIN-27922: fix global gettext override

- group_project_v2/group_project.py
- group_project_v2/stage_components.py
- group_project_v2/templates/html/components/review_assessment.html
- group_project_v2/utils.py
- setup.py
Group work grading was rounding to the nearest even number after py3 upgrade. Added method to round numbers in similar fashion to py2 i.e. round half up approach.
> MCKIN-29429 Changed rounding to be consistent in half up manner
