open-craft/xblock-group-project-v2

group_project_v2/group_project.py
group_project_v2/public/css/components/project_team.css
group_project_v2/public/css/group_project.css
group_project_v2/public/css/project_navigator/project_navigator.css
group_project_v2/public/css/project_navigator/submissions_view.css
group_project_v2/public/js/components/project_team.js
group_project_v2/public/js/components/submission.js
group_project_v2/templates/html/components/project_team.html
group_project_v2/templates/html/components/submission_navigator_view.html

Fixes:
* Popups positioned absolutely (instead of fixed) - should respect parent width and overall look fine. The issue that caused to change this is that long discussion threads span below bottom border of *viewport* and was impossible to view. Now they should just stretch the viewport.
* Centered view selector buttons
* 5px margin between upload button and input
* Fixed upload progress - should be the same as upload input
* Darker close button for nav views - should be `#aaa`
* Project team XBlock have 20px top margin
* Emails to teammember/group - should now hit the proper endpoint in Apros (was broken) and display success/failure messages. Local Apros installs are not configured to send emails, so it will always show an error. There're no indication of success/error though, so if it …

Styling fixes

---

group_project_v2/public/css/group_project.css
group_project_v2/public/js/components/submission.js
group_project_v2/stage_components.py
tests/unit/test_stage_components.py

When user tries uploading a file, if upload is cancelled or failed, non-descriptive "Error" message is shown. This PR fixes passing error messages in case of failed upload and set's up proper message if user have cancelled the upload.
To test:
1. Try uploading the file with some illegal characters in a name (not sure what characters are exactly illegal, but `~` in file name proved to fail the upload).
2. Try cancelling the upload. Cancel button only appears during file upload at the very bottom of the PN. So, to actually use it, big file is needed (I use pycharm tarball - ~140Mb).

Messages for file upload errors and cancel

---

group_project_v2/mixins.py
group_project_v2/stage.py
tests/unit/test_group_project.py
tests/unit/test_project_api.py
tests/unit/test_stages.py
tests/utils.py

Changes in this PR: Team Evaluation Display and Grade Display stages now marked as complete if all the feedback display components ("Team Evaluation Display" and "Grade Evaluation Display) that are configured to show feedback on **required** questions have feedback from all users assigned review:
* For Team Evaluation - all other team members
* For Grade Evaluation - all users that got the group assigned for review.
Testing instructions:
* Add Team Evaluation and Peer Grading stages (+ assign reviews for PG stage in Apros). Mark at least some questions as required.
* Add Team Evaluation Display and Grade Display stages.
* Do not perform any reviews yet.
* Go to Team Eval Display and Grade Display - note they are not marked as complete
* Perform *some* reviews, go to TED stage and GD stage …

Feedback review stages completion conditions

---

group_project_v2/group_project.py
group_project_v2/project_api.py
group_project_v2/stage.py
tests/integration/test_project_navigator.py
tests/integration/test_stages.py
tests/unit/test_project_api.py
tests/unit/test_stages.py

Switched xblocks to use normal progress events instead of API calls to create completion data

Completion events via runtime.publish

---

group_project_v2/group_project.py
group_project_v2/notifications.py
test-requirements.txt
tests/unit/test_notifications.py

**Background:** Group Project XBlock sends notifications for file upload, grades posted and stage open/close dates. Group Project v2 sends the same types of messages, but uses different navigation approach, so the URLs in messages need to be different. For this to work, GP v2 has to send messages of unique types. 
**Description:** This PR switches GP v2 to use dedicated message types
**Dependencies:** This PR is one of the three that fix notifications in Group Project v2 XBlock; the other two are:
* https://github.com/edx-solutions/edx-platform/pull/517 - adds URLResolvers
* https://github.com/edx/edx-notifications/pull/162 - registers new message types
**Related:** [YONK-146](https://openedx.atlassian.net/browse/YONK-146) was caused by changing URL resolvers for GP v1. Should not be …

Dedicated notifications type

---

group_project_v2/stage_components.py

For testing, remove one of the questions the grade feedback blocks in a review step are referring to and publish the unit.  You should be seeing the error message below instead of the affected grade, and the reset of the page (including the project navigator and the other grades) should render normally.

Show error message instead of throwing 500 for misconfigured review step.

---

group_project_v2/api_error.py
group_project_v2/group_project.py
group_project_v2/project_api.py
group_project_v2/project_navigator.py
group_project_v2/public/js/components/project_team.js
group_project_v2/public/js/group_project.js
group_project_v2/public/js/project_navigator/private_discussion_view.js
group_project_v2/public/js/project_navigator/project_navigator.js
group_project_v2/public/js/project_navigator/resources_view.js
group_project_v2/public/js/project_navigator/submissions_view.js
group_project_v2/stage.py
tests/integration/test_general.py
tests/integration/test_project_navigator.py
tests/unit/test_stages.py
tests/utils.py

* https://edx-wiki.atlassian.net/browse/MCKIN-3471 Proficiency score - When graded a group activity for gw v2, the proficiency score does not updated
* https://edx-wiki.atlassian.net/browse/MCKIN-3501 When group has been evaluated, members of that group doesn't received notification for posting grades
* https://edx-wiki.atlassian.net/browse/MCKIN-3502 Page is not loading for IE - 9,10
* https://edx-wiki.atlassian.net/browse/MCKIN-3473 UI - Change order of buttons on Project Navigator => Already fixed in https://github.com/open-craft/xblock-group-project-v2/commit/8ce0ce6d20dd0b82a09aa6463dfc4d6762bfd621 but with the wrong order
1. Score and grade notification - create a graded activity, set min rquired reviews to one (to simplify testing), add peer review stage + …

Fixes from QA - batch 5

---

group_project_v2/group_project.py
group_project_v2/mixins.py
group_project_v2/project_navigator.py
group_project_v2/stage.py
group_project_v2/stage_components.py
group_project_v2/utils.py
requirements.txt

**Description:** Switches GP to use utils versions of nested XBlock support stuff
This changeset only affects studio editing - make sure add/edit/reorder/delete nested XBlocks works as expected (including keeping single child of Project Navigator and Discussion XBlock)

Switch to using xblock-utils nested xblock helpers

---

group_project_v2/group_project.py
group_project_v2/project_navigator.py
group_project_v2/public/js/stages/review_stage.js
group_project_v2/stage/review.py
group_project_v2/stage_components.py
group_project_v2/templates/html/stages/peer_review.html
group_project_v2/templates/html/stages/team_evaluation.html
pylintrc
tests/integration/page_elements.py
tests/integration/test_project_navigator.py
tests/unit/test_group_project.py
tests/unit/test_stages.py
tests/utils.py

**Depends on:** https://github.com/edx-solutions/XBlock/pull/6
1. TA with staff access:
1.1. Grant TA company or internal admin role. 
1.2. Make sure there's at least one TA graded activity (Min required reviews = 0 in studio for activity) with Peer Review stage. 
1.3. Go to Admin -> Group  Work -> Select Course -> Group Work Status -> Choose any group -> Click "TA Graded" in any column.
1.4. You should arrive to Group Project at selected stage. **Expected result:** Can grade group and submit feedback. **Failure condition:** clicking submit does not post feedback.
2. Copy Update - after submitting any upload, the confirmation dialog text should not contain "passes" at the end.
3. Review stages state
3.1. Review stage (both Peer Grading and team Evaluation) stages …

Fixes from QA - batch 6

---

group_project_v2/group_project.py
group_project_v2/stage_components.py

**Description:** If GP contains two or more activities, total course grade used to be calculated incorrectly until all activities received grade, as activities with pending grades were skipped.
1. Create GP with two activities (optionally of different weight), make sure weight is greater than zero for both.
2. Configure course grading (in Studio - Settings -> Grading). One grader with 100% weight is recommended. Configure section with GP to use the grader (course outline -> cog under section name -> grading section).
3. Add one Peer Grading stage with at least one question to both activities. Make sure the question highest response is equal to activity's grade (i.e. if weight is 100 and question is a dropdown, max option value should be 100).
4. Provide grade for …

Activities with pending grades are properly used when calculating course grade

---

group_project_v2/templates/html/components/submission_review_view.html
tests/integration/page_elements.py
tests/integration/test_cross_stage_features.py

**Description:** This PR makes uploader name and upload data unavailable for reviewer on peer grading stage
1. Create and configure Group Project with at least two groups, at least one upload and at least one peer grading stage (upload and stage should be in the same activity).
2. Generate review assignments. (MCKA Admin -> Group Work -> Choose program and course ->  Assignment Info -> Generate review assignments for at least one activity)
3. As any member of group 1, submit an upload.
4. As any member of the other group, navigate to Peer Grading stage. If there are multiple groups/teammembers, make sure you choose the right user here. You might need to try different users to pick the one that reviews that particular group. Alternatively, provide uploads for all …

Removed uploader data from peer grading stage

---

group_project_v2/public/css/group_project.css
group_project_v2/templates/html/project_navigator/ask_ta_view.html

In this episode:
* [MCKIN-3686](https://edx-wiki.atlassian.net/browse/MCKIN-3686) - changing text in ask TA view
* [MCKIN-3688](https://edx-wiki.atlassian.net/browse/MCKIN-3688) - changing username styling to not appear as clickable

UI, copy and styling fixes - part 5

---

group_project_v2/templates/html/components/submission_navigator_view.html
tests/integration/page_elements.py
tests/integration/test_project_navigator.py
tests/utils.py

**Description:** This PR fixes file download issues in Firefox.
**JIRA:** [MCKIN-3711](https://edx-wiki.atlassian.net/browse/MCKIN-3711)
1. Create and configure group work in Studio and Apros. 
1.1. Add Group Work XBlock
1.2. Add Project Navigator and at least one Activity into Group Work XBlock
1.3. Add all Project Navigator views to Project Navigator
1.4. Add at least one Submission stage (aka Upload stage) to Activity
1.5. Add at least one Submission to Submission Stage.
2. Open group work in Apros as student.
3. Open Submissions view in Project Navigator
4. Upload a file (hint: txt, csv, xml or "office" files are usually accepted; images, css/js/html usually don't)
5. *In Firefox* - try downloading file by clicking on the filename. **Expected result:** new …

Firefox file download fix + tests

---

group_project_v2/project_navigator.py
group_project_v2/stage_components.py
tests/integration/page_elements.py
tests/integration/test_project_navigator.py
tests/unit/test_stage_components.py

**Description:** This PR enables TAs to upload files for group.
0. Assign a TA for a course with GPv2: as MCKA Admin go  to MCKA ADMIN -> Roles & Permissions -> select organization -> choose user -> click pencil, check "TA" in for the target course (and maybe "Internal Admin" on top of popup)
1. Log in to Apros as a TA
2. Go to MCKA ADMIN (or Internal Admin)
3. Go to Group Work tab, click "Access Admin Dashboard V2"
4. Select program, course and project
5. Click blue right arrow in any of the stages that have it (only peer grading stages have it so far, so make sure there's at least one of those)
6. Expand any group; clicking on "Group Project" icon (three "users" in circle) - Group project in TA grading mode should open
7. Make sure submissions view is available …

TAs are allowed to upload files for a group

---

group_project_v2/stage/base.py
tests/integration/test_stages.py
tests/unit/test_stages/base.py

Fix for MCKIN-3702. 
Steps to reproduce: 
1. Install Apros and setup group work. 
2. Import GWv2 test curse 
3. Edit this course and set both Open Date And close Date to today
4. Observe that Peer grading phase is closed when you login as a normal user. 
Steps to verify: 
1. Install this version of the group-project v2 xblock. 
2. Observe that peer grading phase is now open.

Fix for MCKIN-3702 close date for stage now means EOD

---

group_project_v2/templates/html/stages/peer_review.html
tests/integration/test_stages.py

Fixes MCKIN-3510. 
**Manual verification**
1. Probably you'll need apros
2. With groupwork set up ;) 
3. Download GWv2 ver 3 course (attached to OC-649) 
4. Import the course, and set up the group work.
5. Add TA student 
6. Go to Group work dashboard and start grading "TA Graded task", you should see orange "Grading View" box on top (this is intended behavior)
7. Go to  Group work dashboard and start grading "Peer review task", you should see the same box as in last point (this is the error) 
Fix verificaiton
1. Install this version of GWv2 
2. Go to  Group work dashboard and start grading "Peer review task" you should see red box with: "TA GRADING OVERRIDE VIEW". 
Running tests
1. I have added tests that verify this functionality. These tests might need some work to use proper idioms …

Fix for invalid header in TA grading view

---

README.md
group_project_v2/group_project.py
group_project_v2/mixins.py
group_project_v2/project_api/api_implementation.py
group_project_v2/project_api/dtos.py
group_project_v2/public/css/group_project_dashboard.css
group_project_v2/stage/base.py
group_project_v2/stage/basic.py
group_project_v2/stage/review.py
group_project_v2/stage_components.py
group_project_v2/templates/html/activity/dashboard_detail_view.html
group_project_v2/utils.py
tests/integration/test_stages.py
tests/unit/test_mixins.py
tests/unit/test_stages/test_peer_review.py
tests/utils.py

What is done: 
What should be done 
**Post-internal review todos**
**Major changes in XBlock logic**
* User needs to have a specific role to access dashboard at all
* Company admins will have the detail dashboard pre-filtered by company, this person is administering, which means he will only have access to groups that contain no students from this company. This filter can't be taken down. 
**Configuration changes** 
Use following ``XBLOCK_SETTINGS``: 
"XBLOCK_SETTINGS": {
"group_project_v2": {
"dashboard_details_url": "/admin/workgroup/dashboard/programs/{program_id}/courses/{course_id}/projects/{project_id}/details?activate_block_id={activity_id}",
"ta_review_url": "/courses/{course_id}/group_work/{group_id}?activate_block_id={activate_block_id}",
"see_dashboard_for_all_orgs_perms": …

OC-1287 Filter by company

---

.gitignore
Makefile
group_project_v2/group_project.py
group_project_v2/public/css/group_project_common.css
group_project_v2/stage/base.py
group_project_v2/stage/basic.py
group_project_v2/stage/review.py
group_project_v2/stage/utils.py
group_project_v2/templates/html/activity/dashboard_detail_view.html
group_project_v2/utils.py
requirements/test.txt
tests/unit/test_stages/base.py
tests/unit/test_stages/test_base_stage.py
tests/unit/test_stages/test_basic.py
tests/unit/test_stages/test_peer_review.py

**Description:** This PR switches "external" status display to using labels instead of icons and enables Submission Stages display in dashboard detail view.
**JIRA:** [MCKIN-3841](https://edx-wiki.atlassian.net/browse/MCKIN-3841), [MCKIN-3842](https://edx-wiki.atlassian.net/browse/MCKIN-3842)
0. Configure Group Project (see docs in `documentation` branch).
1. Log in to Apros as admin.
2. Go to MCKA ADMIN -> Group Project -> Access V2 Dashboard.
3. Choose Program, course and project - dashboard view should be diplayed
4. *New in this PR:* Submission stages should now have white background and blue arrow in bottom-right corner.
5. Click on any of the blue arrows to jump to dashboard details view
6. *New in this PR:* Submission and Peer Grading stage should display …

Status labels

---

group_project_v2/notifications.py
group_project_v2/stage_components.py
tests/unit/test_notifications.py
tests/unit/test_stage_components.py

@e-kolpakov This PR fixes issue related to wrong notification urls being generated for `open-edx.xblock.group-project-v2.file-uploaded` messages. As we discussed yesterday moving file upload notification to `StageNotificationsMixin` fixes the issue. Please review.

file upload notification url should have stage location instead of activity

---

group_project_v2/group_project.py
group_project_v2/notifications.py
tests/unit/test_group_project.py
tests/unit/test_notifications.py
tests/utils.py

@e-kolpakov this PR modifies `ActivityNotificationsMixin` to send timed notifications for `grades-posted` events. Time of notification is calculated by enumerating stages of activity for oldest grade display stage date. Could you please review this one?

send timed notifications for grades-posted activity

---

group_project_v2/notifications.py
tests/unit/test_notifications.py

Notifications seems to be ignored when we set `send_at` to current datetime due to this statement
https://github.com/edx/edx-notifications/blob/master/edx_notifications/lib/publisher.py#L254
I'm not setting `ignore_if_past_due` to `False` to avoid notifications being ignored.
@e-kolpakov could you please review?.

notifications should not be ignored

---

group_project_v2/group_project.py
group_project_v2/notifications.py
tests/unit/test_group_project.py
tests/unit/test_notifications.py
tests/utils.py

@e-kolpakov I moved `fire_grades_posted_notification` from `ActivityNotificationsMixin` to `StageNotificationsMixin`. That would allow us getting grade display stage location for notification links. I have done some refactoring to generate timed notification even if grade display datetime is past. Could you please review?

moved fire_grades_posted_notification from ActivityNotificationsMixin to StageNotificationsMixin

---

group_project_v2/public/css/group_project_dashboard.css
group_project_v2/templates/html/activity/dashboard_detail_view.html
group_project_v2/templates/html/stages/dashboard_detail_view.html
tests/js/fixtures/dashboard_detail_view.html

JIRA: OC-1439
Simple swap of one Font Awesome icon for another.
Before:
After:

Replace envelope icon with download icon

---

group_project_v2/group_project.py
group_project_v2/stage/base.py
group_project_v2/stage/basic.py
tests/unit/test_stages/test_base_stage.py
tests/unit/test_stages/test_basic.py
tests/unit/test_stages/test_peer_review.py
tests/unit/test_stages/test_submission.py

1. Have an apros devstack set up. 
2. Install a GWv2 showcase course and set it up. 
3. Login as admin user, and go to the GWv2 dashboard. Note that Upload stage now displays as grayed out. 
4. Go to Detail dashboard and note that upload stage is still displayed on the detail view.

Fix for MCKIN-1446 upload stage is not showing as graded stage.

---

group_project_v2/public/css/group_project_dashboard.css
group_project_v2/stage/base.py
group_project_v2/templates/html/stages/dashboard_view.html
tests/unit/test_stages/test_base_stage.py

#. Verification
1. Have working solutions devstack. 
2. Have Group Work 2 configured. 
3. Have a Program Foo, to which Group Work course named Course Foo belong
4. You need to have two companies: 
a. One with some students attached to a group project (company A)
b. One without students attached to this project, but company should be participating in a Program A. (Company B)
5. Go to GWv2 dashboard, select program, course, project, and select Company A, observe that stats add to 100%. 
6. Select company B, and observe that stats don't add to 100%, and look like that: 
#. Testing
7. Check out this branch, go to GWv2 and select Company B, observe that you see stats with empty set symbol, and a tooltip explaining situation.

When there is no students in groups inform user of this

---

group_project_v2/project_api/api_implementation.py
group_project_v2/utils.py
requirements/test.txt
tests/unit/project_api/test_project_api.py

This PR has changes to stop prefixing of server address to a url if url is absolute. It fixes a bug report in https://openedx.atlassian.net/browse/YONK-448
I had to set django-nose to 1.4.1 explicitly since requirements in xblock-sdk install 1.4.4 which breaks running of python tests since django-nose 1.4.4 does not support old versions(< 1.8) of django.
@e-kolpakov would you please review this?

Don't prefix server address if url is absolute

---

group_project_v2/project_api/api_implementation.py
tests/unit/project_api/test_project_api.py

@e-kolpakov PR #108 introduced a glitch which break building of url when any or the `url_parts` has a non-string value. This PR fixes that glitch.
Here is the traceback or the error.
```
Traceback (most recent call last):
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
return func(*args, **kwargs)
File "/edx/app/edxapp/edx-platform/lms/djangoapps/courseware/module_render.py", line 1189, in xblock_view
fragment = instance.render(view_name, context=request.GET)
File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/ …
```

type cast url_parts to string

---

group_project_v2/project_api/api_implementation.py
tests/unit/project_api/canned_responses.py
tests/unit/project_api/test_project_api.py

`dashboard_view` of group project v2 call Projects API to get some of the data needs to be rendered. This API now returns a paginated response having projects info in `results` key
```
{"count":1,"num_pages":1,"current_page":1,"results":[{"id":274,"url":"http://integration.mckinsey.edx.org/api/server/projects/274/","created":"2016-11-12T11:28:15Z","modified":"2016-11-12T11:28:15Z","course_id":"ET1/ET01/2016","content_id":"i4x://ET1/ET01/gp-v2-project/1b4fc43f58a14705bb6c4f0e68f4cbaa","organization":221,"workgroups":[3154,3155,3156,3157,3158,3159]}],"next":null,"start":0,"previous":null}
```
This PR makes these changes to fix admin dashboard of group project. Actual bug with step to reproduce are list [here](https://openedx.atlassian.net/browse/YONK-474)
@bradenmacdonald can some one in …

fix to accommodate paginated result returned by projects API

---

.travis.yml
setup.py

When installed via pip (not using `-e`), two modules were missing: `group_project_v2.stage` and `group_project_v2.project_api`
Testing instructions:
1. Create and activate a Python 2.7 virtualenv
1. Run `pip install 'git+https://github.com/edx/xblock-utils.git@v1.0.3#egg=xblock-utils==1.0.3'`
1. Compare the result of
```
pip install 'git+https://github.com/open-craft/xblock-group-project-v2.git@0.4.2#egg=xblock-group-project-v2==0.4.2'
```
with
```
pip install 'git+https://github.com/open-craft/xblock-group-project-v2.git@fix-setup-py#egg=xblock-group-project-v2==0.4.3'
```
The former will be missing the `group_project_v2.stage` and `group_project_v2.project_api` modules, while the latter should correctly install them.

Fix packages in setup.py

---

group_project_v2/project_api/dtos.py
group_project_v2/stage_components.py
group_project_v2/templates/html/components/peer_selector.html
group_project_v2/templates/html/components/project_team.html

xblock group project v2 calls users API and expects `avatar_url` for user profile image url while users API has been updated to to return profile_image dictionary which contains urls to different size profile images. 
New Response contains a dict of profile_images:
```
"profile_image": {
"image_url_full": "https://qa.mckinsey.edx.org/static/images/profiles/default_500.4215dbe8010f.png",
"image_url_large": "https://qa.mckinsey.edx.org/static/images/profiles/default_500.4215dbe8010f.png",
"image_url_medium": "https://qa.mckinsey.edx.org/static/images/profiles/default_160.d50822e97e4a.png",
"image_url_small": "https://qa.mckinsey.edx.org/static/images/profiles/default_48.bcde3c9b8ab8.png",
"has_image": false
}
```
This PR updates xblock group project V2 to use that new response. …

MCKIN-6182: fix user profile image url according to updated users api

---

group_project_v2/stage_components.py

This PR fixes profile image display issue on team evaluation stage page.
Before fix:
After fix:
@bradenmacdonald would you please review?

MCKIN-6282: fix profile image display issue on team evaluation stage

---

setup.py

Includes fixes from https://github.com/open-craft/xblock-group-project-v2/pull/116

Bump version to 0.4.5.

---

group_project_v2/public/js/components/submission.js
package.json
setup.py

Fixes bug where pasting rich clipboard data containing both an image and text component can cause the image component to be uploaded as a file when trying to paste the text component in a textbox. 
**JIRA tickets**: MCKIN-7806 / OC-4789

Fix bug with automatic upload of clipboard images

---

group_project_v2/mixins.py
group_project_v2/project_navigator.py
group_project_v2/stage_components.py
requirements/base.txt
tests/unit/test_mixins.py

Resolves [OC-5161](https://tasks.opencraft.com/browse/OC-5161) 
All group project blocks should be excluded from completion, as described in the ticket.
* The tests use a new method on XBlock, so there's an added PR over there.  Before merging, the requirement should be updated to use a tagged release of XBlock.  If that takes too long to merge, the tests here can be altered to manually calculate the completion_mode. (edx/XBlock#385)
* I tried to spend a little time making this xblock python-3 compatible before starting work on this ticket.  That work  was blocked by incompatibility in https://github.com/edx/edx-notifications, which proved too difficult to update simply (lots of manual checking for str vs unicode).  The work on making group_project_v2 python3 compatible is incomplete, but …

Ensure all block types are excluded from completion.

---

requirements/base.txt
setup.py

@xitij2000 Here's the version bump.  Note that the current build should be fine, because the xblock version is defined as >0.4,<2.0 in the setup.py, which is where it matters when it gets pip installed.

MCKIN-8797: Bump required xblock versions.

---

setup.py

https://github.com/open-craft/xblock-group-project-v2/pull/126 was merged with a issue that only was perceived while the CI on edx-platform was run. The dependency links on `setup.py` file need to have a specific name to work, e.g. `#egg=django-upload-validator-1.0.2` (`package_name-version`).
This PR fixes that typo.
1. Clone this branch.
2. On a python 2.7 venv, run `pip install -e . --process-dependency-links` and check that the setup is completed successfully.
**Reviewers:**

YONK-1306: Hotfix setup.py issue

---

group_project_v2/public/js/project_navigator/ask_ta_view.js
setup.py

New UI in apros is based on bootstrap instead of foundation. Used bootstrap to show modal if the foundation is undefined. 
Issue: https://edx-wiki.atlassian.net/browse/MCKIN-10341

MCKIN-10341 -- Fixed modal for bootstrap

---

requirements/base.txt
setup.py

Downgrading Django storage to 1.4.1 because it is failing tests on edx platform

MCKIN-11136-django-storage-downgrade

---

requirements/base.txt
setup.py

Issue: Boto3 was not being used in edx-platform before ironwood release but it has been added in ironwood now. Ironwood is using `boto3==1.4.8` and this library is also being used in xblock-group-project-v2. In Xblock the boto3 version is 1.9.173 which is resulting in version conflict with edx-platform.
This PR downgrades `boto3` version to `1.4.8` for `xblock-group-project-v2` to make it compatible with `ironwood` release of `edx-platform`.

MCKIN-12639: downgrade boto3 to 1.4.8 to fix conflict with ironwood

---

group_project_v2/public/js/project_navigator/resources_view.js
group_project_v2/stage_components.py
group_project_v2/templates/html/components/video_resource.html
group_project_v2/templates/html/project_navigator/resources_view.html

This PR adds support for Brightcove video playback in GW GroupProjectVideoResourceXBlock. Currently only Ooyala video is supported.
**Testing Instructions:**
1. Install this branch in devstack. Author a `Group Project V2` unit in a course from Studio. 
2. Add a `Group Project Activity` component in it.
3. Add a `Completion Stage` component in Group Project Activity.
4. Add a `Video Resource` 
5. Make sure both Ooyala and Brightcove videos play fine when rendered on Apros
Sample BC video: `6068614553001`
Sample Ooyala video: `80Z21uNzE6nDAecFlIaDYCweyWk75Kap`

MCKIN-12706: Support for Brightcove video resource playback

---

group_project_v2/templates/html/components/video_resource.html
setup.py

`playsinline` attribute added in Brightcove embed template to support inline video play

playsinline attribute added to support inline video play

---

group_project_v2/group_project.py
group_project_v2/mixins.py
group_project_v2/project_navigator.py
group_project_v2/stage/base.py
group_project_v2/stage/basic.py
group_project_v2/stage_components.py
group_project_v2/utils.py
setup.py

Description
------------
This PR replaces usage of the deprecated `xblock.fragment.Fragment` with `web_fragments.fragment.Fragment`
This also requires changes to method used to load resources from fragments.
Testing
--------
1. Make sure to have a course containing group work present, import the sample one if necessary:
```(venv) edxapp@vagrant:~/edx-platform$ ./manage.py cms import /edx/var/edxapp/data/ $(pwd)/xblock-group-project-v2/examples/T1/```
1. Ensure loading the Group Work dashboardV2 works correctly.

Update deprecated xblock.fragment to web_fragments.fragment

---

group_project_v2/stage/review.py
setup.py

Right now submit view is returning `{result': 'error', 'msg': 'Bad Request'}` and it doesn't expose any information's which makes it hard to debug in case of bulk upload. 
AC: Update the endpoint to return the original error i.e. thrown by Projects API, so that we can show the exact error against feedback uploaded for each group(in case if there are any.)

MCKIN-22507 Exposed API errors to response for tracking

---

group_project_v2/mixins.py
setup.py

This helps to suppress the logs produce in group project when accessed through studio.
Since in studio real_user is not available and this gives us unnecessary logs.
**JIRA tickets**: [BB-2920](https://tasks.opencraft.com/browse/BB-2920)
~~**Sandbox URL**: TBD - sandbox is being provisioned.~~
**Testing instructions**:
1. Get the ironwood box working with edx-solutions/edx-platform code
2. Check-in  `edx-platform` that it is on the development branch
3. Make sure to have created a user or a super-user to test you can do it by running `python manage.py lms createsuperuser`
4. When you have done `vagrant ssh` you need to change the user `sudo -u edxapp -Hs`
5. Clone this repository in appropriate location
6. Acvtivate the virtualenvironment `source /edx/app/edxapp/venvs/edxapp/bin/acitvate` …

[YONK-1748] [BB-2920] Suppress the logs produce in group project when accessed through studio

---

.travis.yml
package-lock.json
package.json

Upgrades the npm packages to latest versions to get rid of security warnings. 
Splits the travis config to run javascript tests separately and once.

Upgrade packages to get rid of security warning

---

group_project_v2/public/js/group_project_common.js
setup.py

This PR fixes global `gettext` override due to which `gettext` was unable to access translations catalog other than gpv2 hence no other translations were working.

MCKIN-27922: fix global gettext override

---

group_project_v2/json_requests.py
setup.py

GW Deliverables upload fails with on Py3. 
```
group_project_v2/json_requests.py", line 63, in POST
edx.devstack-juniper.lms |     return urlopen(url_request, json.dumps(data), TIMEOUT)
edx.devstack-juniper.lms |   File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
edx.devstack-juniper.lms |     return opener.open(url, data, timeout)
edx.devstack-juniper.lms |   File "/usr/lib/python3.5/urllib/request.py", line 464, in open
edx.devstack-juniper.lms |     req = meth(req)
edx.devstack-juniper.lms |   File "/usr/lib/python3.5/urllib/request.py", line 1190, in do_request_
edx.devstack-juniper.lms |     raise TypeError(msg)
edx.devstack-juniper.lms | TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.
```
Converting str to btyes to fix that.

MCKIN-28448 - Deliverables are not uploading

---

group_project_v2/json_requests.py
group_project_v2/utils.py
setup.py

This fixes PUT data encoding and exceptions messages:
```
t_v2/json_requests.py", line 39, in make_request
edx.devstack-juniper.lms |     response = func(*args, **kwargs)
edx.devstack-juniper.lms |   File "/edx/src/xblock-group-project-v2/group_project_v2/json_requests.py", line 81, in PUT
edx.devstack-juniper.lms |     return opener.open(request, None, TIMEOUT)
edx.devstack-juniper.lms |   File "/usr/lib/python3.5/urllib/request.py", line 464, in open
edx.devstack-juniper.lms |     req = meth(req)
edx.devstack-juniper.lms |   File "/usr/lib/python3.5/urllib/request.py", line 1190, in do_request_
edx.devstack-juniper.lms |     raise TypeError(msg)
edx.devstack-juniper.lms | TypeError: POST data should be bytes or an iterable of bytes. It cannot be of type str.
edx.devstack-juniper.lms | …
```

MCKIN-28362 - Encoding and exception formatting fixed
